pokemon_types = {
    'Rattata': ['Normal'],
    'Aerodactyl': ['Rock', 'Flying'],
    'Tentacool': ['Water', 'Poison'],
    'Slowpoke': ['Water', 'Psychic'],
    'Magikarp': ['Water'],
    'Bulbasaur': ['Grass', 'Poison'],
    'Horsea': ['Water'],
    'Squirtle': ['Water'],
    'Vulpix': ['Fire'],
    'Oddish': ['Grass', 'Poison'],
    'Venonat': ['Bug', 'Poison'],
    'Lickitung': ['Normal'],
    'Zubat': ['Poison', 'Flying'],
    'Seel': ['Water'],
    'Dratini': ['Dragon'],
    'Caterpie': ['Bug'],
    'Mr. Mime': ['Psychic', 'Fairy'],
    'Voltorb': ['Electric'],
    'Articuno': ['Ice', 'Flying'],
    'Farfetchd': ['Normal', 'Flying'],
    'Shellder': ['Water'],
    'Cubone': ['Ground'],
    'Sandshrew': ['Ground'],
    'Drowzee': ['Psychic'],
    'Omanyte': ['Rock', 'Water'],
    'Porygon': ['Normal'],
    'Machop': ['Fighting'],
    'Staryu': ['Water'],
    'Koffing': ['Poison'],
    'Zapdos': ['Electric', 'Flying'],
    'Mew': ['Psychic'],
    'Doduo': ['Normal', 'Flying'],
    'Scyther': ['Bug', 'Flying'],
    'Abra': ['Psychic'],
    'Moltres': ['Fire', 'Flying'],
    'Weedle': ['Bug', 'Poison'],
    'Magnemite': ['Electric', 'Steel'],
    'Pinsir': ['Bug'],
    'Rhyhorn': ['Ground', 'Rock'],
    'Diglett': ['Ground'],
    'Kangaskhan': ['Normal'],
    'Charmander': ['Fire'],
    'Pidgey': ['Normal', 'Flying'],
    'Tauros': ['Normal'],
    'Ditto': ['Normal'],
    'Lapras': ['Water', 'Ice'],
    'Pikachu': ['Electric'],
    'Meowth': ['Normal'],
    'Eevee': ['Normal'],
    'Geodude': ['Rock', 'Ground'],
    'Psyduck': ['Water'],
    'Growlithe': ['Fire'],
    'Mankey': ['Fighting'],
    'Grimer': ['Poison'],
    'Bellsprout': ['Grass', 'Poison'],
    'Ekans': ['Poison'],
    'Spearow': ['Normal', 'Flying'],
    'Goldeen': ['Water'],
    'Gastly': ['Ghost', 'Poison'],
    'Ponyta': ['Fire'],
    'Tangela': ['Grass'],
    'Poliwag': ['Water'],
    'Exeggcute': ['Grass', 'Psychic']
}

import shutil
import glob
for key, value in pokemon_types.items():
    for i in value:
        for j in glob.glob("/home/mir/Desktop/PokemonProject/kagglePokemonSet/archive/pokemon/"+ str(key)+"/*"):
            shutil.copy(j, "/home/mir/Desktop/PokemonProject/kagglePokemonSetType/archive/types/"+str(i))